apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend
  namespace: production 
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: backend
  template:
    metadata:
      labels: 
        app:  backend
    spec:
      serviceAccountName: backend-serviceaccount
      containers:
      - name: backend
        image: gowdaamith/k8s-backend:1.2
        ports:
          - containerPort: 8000
        
        

        resources: 
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits: 
            cpu: "500m"
            memory: "265Mi"
        env: 
          - name: APP_ENV
            valueFrom: 
              configMapKeyRef: 
                name: backend-config
                key: APP_ENV
          - name: DB_USERNAME
            valueFrom: 
              configMapKeyRef:
                name: backend-config
                key: DB_USERNAME
          - name: DB_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: backend-secret
                key: DB_PASSWORD



